---
abstract: 'A perl sentry client'
author:
  - 'Rentrak Corporation'
build_requires:
  ExtUtils::MakeMaker: '0'
  HTTP::Response: '0'
  Test::CPAN::Changes::ReallyStrict: '0'
  Test::LWP::UserAgent: '0'
  Test::More: '0.88'
  Test::Perl::Critic: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.140640'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Sentry-Raven
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dump: '0'
  DateTime: '0'
  Devel::StackTrace: '0'
  English: '0'
  HTTP::Status: '0'
  JSON::XS: '0'
  LWP::Protocol::https: '0'
  LWP::UserAgent: '0'
  Moo: '0'
  MooX::Types::MooseLike::Base: '0'
  Sys::Hostname: '0'
  URI: '0'
  UUID::Tiny: '0'
  perl: '5.008'
resources:
  repository: https://github.com/rentrak/perl-raven
version: '0.04'
x_homepage: https://github.com/rentrak/perl-raven
